import React from "react";
import PropTypes from "prop-types";
import {
  Utensils,
  ShoppingCart,
  TrainFront,
  Plane,
  ShoppingBag,
  Clapperboard,
  BriefcaseMedical,
  Dumbbell,
  Zap,
  BookOpen,
  Coffee,
  Ellipsis,
  Star,
  House,
  Gift,
  Dog,
  Music,
  Gamepad2,
  Bike,
  Car,
  GraduationCap,
  Briefcase,
  Heart,
  Baby,
  Phone,
  Wifi,
  Cat,
  Beer,
  Pizza,
  Flower2,
  Wallet,
  Landmark,
  Tv,
  Shirt,
  Droplets,
  Shield,
  CreditCard,
  CircleHelp,
  Umbrella,
  Banknote,
  ShoppingBasket,
} from "lucide-react";

export const categoryIcons = {
  food: Utensils,
  cart: ShoppingCart,
  train: TrainFront,
  airplane: Plane,
  shopping: ShoppingBag,
  movie: Clapperboard,
  "medical-bag": BriefcaseMedical,
  dumbbell: Dumbbell,
  "lightning-bolt": Zap,
  "book-open-variant": BookOpen,
  coffee: Coffee,
  "dots-horizontal": Ellipsis,
  star: Star,
  home: House,
  gift: Gift,
  dog: Dog,
  music: Music,
  "gamepad-variant": Gamepad2,
  bike: Bike,
  car: Car,
  school: GraduationCap,
  briefcase: Briefcase,
  heart: Heart,
  "baby-carriage": Baby,
  phone: Phone,
  wifi: Wifi,
  cat: Cat,
  beer: Beer,
  pizza: Pizza,
  flower: Flower2,
  wallet: Wallet,
  bank: Landmark,
  television: Tv,
  "tshirt-crew": Shirt,
  water: Droplets,
  shield: Shield,
  "credit-card": CreditCard,
};
const legacyIcons = {
  fastfood: Utensils,
  restaurant: Utensils,
  commute: TrainFront,
  flight: Plane,
  entertainment: Clapperboard,
  health: BriefcaseMedical,
  fitness: Dumbbell,
  grocery: ShoppingBasket,
  utilities: Zap,
  rent: House,
  salary: Banknote,
  other: Ellipsis,
  beachaccess: Umbrella,
  "train-car": TrainFront,
  "silverware-fork-knife": Utensils,
  basket: ShoppingBasket,
  flash: Zap,
  cash: Banknote,
};

export default function CategoryIcon({ name, size }) {
  const key = (name || "").toLowerCase();
  const Icon = categoryIcons[key] || legacyIcons[key] || CircleHelp;
  return <Icon size={size} aria-hidden="true" />;
}
CategoryIcon.propTypes = { name: PropTypes.string, size: PropTypes.number };
CategoryIcon.defaultProps = { name: null, size: 18 };
